package com.privatereader.backup

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import com.privatereader.config.AppProperties
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.jdbc.core.simple.JdbcClient
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import org.springframework.mock.web.MockMultipartFile
import java.nio.file.Files

class BackupServiceTest {
    private lateinit var jdbc: JdbcClient
    private lateinit var service: BackupService

    @BeforeEach
    fun setUp() {
        val dataSource = DriverManagerDataSource("jdbc:h2:mem:backup-${System.nanoTime()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "")
        jdbc = JdbcClient.create(dataSource)
        listOf(
            "create table users (id bigint primary key, username varchar(120), display_name varchar(120))",
            "create table books (id bigint generated by default as identity primary key, title varchar(255))",
            "create table book_files (id bigint generated by default as identity primary key, book_id bigint, file_hash varchar(128) unique, storage_path varchar(255), format varchar(20), source_id bigint, source_missing boolean default false)",
            "create table book_formats (id bigint generated by default as identity primary key, book_id bigint)",
            "create table book_content_versions (id bigint generated by default as identity primary key, book_id bigint, source_file_id bigint)",
            "create table book_content_blocks (id bigint generated by default as identity primary key, content_version_id bigint)",
            "create table book_resources (book_id bigint, resource_id varchar(255))",
            "create table library_sources (id bigint primary key)",
            "create table library_source_files (id bigint primary key)",
            "create table import_jobs (id bigint primary key)",
            "create table plugin_registry (id bigint primary key)",
            "create table plugin_error_logs (id bigint primary key)",
            "create table user_book_access (user_id bigint, book_id bigint, granted_by bigint, granted_at timestamp with time zone, primary key(user_id, book_id))",
            "create table user_book_groups (user_id bigint, book_id bigint, group_name varchar(120), updated_at timestamp with time zone, primary key(user_id, book_id))",
            "create table annotations (id bigint generated by default as identity primary key, user_id bigint, book_id bigint, quote_text varchar(255), note_text varchar(255), color varchar(32), anchor_json varchar(255), version integer, deleted boolean, created_at timestamp with time zone, updated_at timestamp with time zone)",
            "create table bookmarks (id bigint generated by default as identity primary key, user_id bigint, book_id bigint, location varchar(255), label varchar(255), deleted boolean, created_at timestamp with time zone, updated_at timestamp with time zone)",
            "create table reading_progress (user_id bigint, book_id bigint, location varchar(255), progress_percent double, updated_at timestamp with time zone, primary key(user_id, book_id))",
            "create table reading_history (user_id bigint, book_id bigint, last_read_at timestamp with time zone, primary key(user_id, book_id))",
        ).forEach { jdbc.sql(it).update() }
        jdbc.sql("insert into users values (1, 'source', 'Source'), (2, 'target', 'Target')").update()
        jdbc.sql("insert into books values (10, 'Book')").update()
        jdbc.sql("insert into book_files (id, book_id, file_hash, storage_path, format, source_missing) values (100, 10, :hash, 'unused', 'epub', false)")
            .param("hash", "cc2b3c1b8c1bf7f2721ef712236cebbc962da100b12e35ed0ea204370c52bdd5").update()
        jdbc.sql("insert into user_book_access values (1, 10, 1, current_timestamp)").update()
        jdbc.sql("insert into annotations (user_id, book_id, quote_text, note_text, color, anchor_json, version, deleted, created_at, updated_at) values (1, 10, 'quote', 'note', 'yellow', '{}', 1, false, current_timestamp, current_timestamp)").update()
        jdbc.sql("insert into bookmarks (user_id, book_id, location, label, deleted, created_at, updated_at) values (1, 10, 'chapter-1', 'source bookmark', false, current_timestamp, current_timestamp)").update()
        jdbc.sql("insert into reading_progress values (1, 10, 'chapter-1', 42.5, current_timestamp)").update()
        jdbc.sql("insert into reading_history values (1, 10, current_timestamp)").update()
        service = BackupService(
            jdbc,
            JdbcTemplate(dataSource),
            ObjectMapper().registerKotlinModule(),
            AppProperties(storageRoot = "build/test-storage"),
        )
    }

    @Test
    fun `user backup restores reading data to explicitly mapped target user`() {
        val archive = service.export(BackupExportRequest(scope = BackupScope.USER_DATA, userIds = setOf(1)))
        val preview = service.preview(MockMultipartFile("file", "backup.zip", "application/zip", archive))

        assertEquals(listOf(1L), preview.sourceUsers.map { it.id })
        val result = service.restore(
            MockMultipartFile("file", "backup.zip", "application/zip", archive),
            actorId = 2,
            request = BackupRestoreRequest(
                scope = BackupScope.USER_DATA,
                userMappings = mapOf(1L to 2L),
                mode = UserDataRestoreMode.REPLACE,
            ),
        )

        assertEquals(1, result.annotations)
        assertEquals(2L, jdbc.sql("select user_id from annotations where user_id = 2").query(Long::class.java).single())
        assertEquals(42.5, jdbc.sql("select progress_percent from reading_progress where user_id = 2").query(Double::class.java).single())
        assertEquals(1, result.histories)
        assertEquals(1L, jdbc.sql("select count(*) from reading_history where user_id = 2").query(Long::class.java).single())
    }

    @Test
    fun `user backup exports only selected users books and data types`() {
        val archive = service.export(
            BackupExportRequest(
                scope = BackupScope.USER_DATA,
                userIds = setOf(1),
                bookIds = setOf(10),
                dataTypes = setOf(UserDataType.ANNOTATIONS, UserDataType.READING_HISTORY),
            ),
        )

        val preview = service.preview(MockMultipartFile("file", "backup.zip", "application/zip", archive))

        assertEquals(2, preview.formatVersion)
        assertEquals(setOf(UserDataType.ANNOTATIONS, UserDataType.READING_HISTORY), preview.dataTypes)
        assertEquals(1, preview.annotations)
        assertEquals(1, preview.histories)
        assertEquals(0, preview.progresses)
    }

    @Test
    fun `book backup restores selected book and original file`() {
        val sourceFile = Files.createTempFile("private-reader-book-backup", ".epub")
        Files.write(sourceFile, "book-content".toByteArray())
        jdbc.sql("update book_files set storage_path=:path where id=100")
            .param("path", sourceFile.toAbsolutePath().toString()).update()
        val archive = service.export(BackupExportRequest(scope = BackupScope.BOOKS, bookIds = setOf(10)))
        val preview = service.preview(MockMultipartFile("file", "books.zip", "application/zip", archive))
        assertEquals(BackupScope.BOOKS, preview.scope)
        assertEquals(1, preview.books)

        jdbc.sql("delete from book_files").update()
        jdbc.sql("delete from books").update()
        val result = service.restore(
            MockMultipartFile("file", "books.zip", "application/zip", archive),
            actorId = 2,
            request = BackupRestoreRequest(scope = BackupScope.BOOKS),
        )

        assertEquals(1, result.restoredBooks)
        assertEquals("Book", jdbc.sql("select title from books").query(String::class.java).single())
        val restoredPath = jdbc.sql("select storage_path from book_files").query(String::class.java).single()
        assertEquals("book-content", Files.readString(java.nio.file.Path.of(restoredPath)))
    }

    @Test
    fun `full backup restores selected user and data types without touching other data`() {
        val archive = service.export(BackupExportRequest(scope = BackupScope.FULL))
        jdbc.sql("insert into annotations (user_id, book_id, quote_text, note_text, color, anchor_json, version, deleted, created_at, updated_at) values (2, 10, 'target quote', 'keep annotation', 'blue', '{\"target\":true}', 1, false, current_timestamp, current_timestamp)").update()
        jdbc.sql("insert into bookmarks (user_id, book_id, location, label, deleted, created_at, updated_at) values (2, 10, 'target-location', 'replace bookmark', false, current_timestamp, current_timestamp)").update()
        jdbc.sql("insert into reading_progress values (2, 10, 'target-progress', 99.0, current_timestamp)").update()
        jdbc.sql("insert into reading_history values (2, 10, current_timestamp)").update()

        val result = service.restore(
            MockMultipartFile("file", "full.zip", "application/zip", archive),
            actorId = 2,
            request = BackupRestoreRequest(
                scope = BackupScope.USER_DATA,
                userMappings = mapOf(1L to 2L),
                mode = UserDataRestoreMode.REPLACE,
                dataTypes = setOf(UserDataType.BOOKMARKS, UserDataType.READING_HISTORY),
            ),
        )

        assertEquals(BackupScope.USER_DATA, result.scope)
        assertEquals(0, result.annotations)
        assertEquals(1, result.bookmarks)
        assertEquals(1, result.histories)
        assertEquals(0, result.progresses)
        assertEquals("source bookmark", jdbc.sql("select label from bookmarks where user_id = 2").query(String::class.java).single())
        assertEquals("keep annotation", jdbc.sql("select note_text from annotations where user_id = 2").query(String::class.java).single())
        assertEquals(99.0, jdbc.sql("select progress_percent from reading_progress where user_id = 2").query(Double::class.java).single())
    }

    @Test
    fun `full backup can restore books without replacing users`() {
        val sourceFile = Files.createTempFile("private-reader-full-book-backup", ".epub")
        Files.write(sourceFile, "book-content".toByteArray())
        jdbc.sql("update book_files set storage_path=:path where id=100")
            .param("path", sourceFile.toAbsolutePath().toString()).update()
        val archive = service.export(BackupExportRequest(scope = BackupScope.FULL))
        jdbc.sql("delete from book_files").update()
        jdbc.sql("delete from books").update()

        val result = service.restore(
            MockMultipartFile("file", "full.zip", "application/zip", archive),
            actorId = 2,
            request = BackupRestoreRequest(scope = BackupScope.BOOKS),
        )

        assertEquals(BackupScope.BOOKS, result.scope)
        assertEquals(1, result.restoredBooks)
        assertEquals(2L, jdbc.sql("select count(*) from users").query(Long::class.java).single())
        val restoredPath = jdbc.sql("select storage_path from book_files").query(String::class.java).single()
        assertEquals("book-content", Files.readString(java.nio.file.Path.of(restoredPath)))
    }
}
