create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(120) not null unique,
    password_hash varchar(255) not null,
    role varchar(40) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists auth_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    access_token_hash varchar(128) not null unique,
    refresh_token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    refresh_expires_at timestamp with time zone not null,
    revoked boolean not null default false,
    created_at timestamp with time zone not null
);

create table if not exists books (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    author varchar(255),
    group_name varchar(120),
    description text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

alter table books add column if not exists group_name varchar(120);

create table if not exists book_files (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id) on delete cascade,
    plugin_id varchar(120) not null,
    file_hash varchar(128) not null unique,
    storage_path text not null,
    source_type varchar(64) not null,
    source_id bigint,
    source_path text,
    format varchar(32) not null,
    file_size bigint not null,
    source_missing boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists book_formats (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id) on delete cascade,
    plugin_id varchar(120) not null,
    format varchar(32) not null,
    capabilities_json text not null,
    manifest_json text,
    online_readable boolean not null default false,
    index_excerpt text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists book_content_versions (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id) on delete cascade,
    source_file_id bigint not null references book_files(id) on delete cascade,
    content_model varchar(64) not null,
    status varchar(32) not null,
    checksum varchar(128) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists book_content_blocks (
    id bigint generated by default as identity primary key,
    content_version_id bigint not null references book_content_versions(id) on delete cascade,
    chapter_index integer not null,
    block_index integer not null,
    block_type varchar(32) not null,
    anchor varchar(255) not null,
    text text not null,
    plain_text text not null,
    meta_json text,
    created_at timestamp with time zone not null
);

create index if not exists idx_book_content_versions_book_status
    on book_content_versions (book_id, status, id desc);

create index if not exists idx_book_content_blocks_version_chapter_block
    on book_content_blocks (content_version_id, chapter_index, block_index);

create table if not exists user_book_access (
    user_id bigint not null references users(id) on delete cascade,
    book_id bigint not null references books(id) on delete cascade,
    granted_by bigint not null references users(id),
    granted_at timestamp with time zone not null,
    primary key (user_id, book_id)
);

create table if not exists annotations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_id bigint not null references books(id) on delete cascade,
    quote_text text,
    note_text text,
    color varchar(32),
    anchor_json text not null,
    version integer not null,
    deleted boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists bookmarks (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_id bigint not null references books(id) on delete cascade,
    location text not null,
    label varchar(255),
    deleted boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists reading_progress (
    user_id bigint not null references users(id) on delete cascade,
    book_id bigint not null references books(id) on delete cascade,
    location text not null,
    progress_percent double precision not null,
    updated_at timestamp with time zone not null,
    primary key (user_id, book_id)
);

create table if not exists library_sources (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    root_path text not null,
    enabled boolean not null default true,
    source_type varchar(64) not null,
    last_scan_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists import_jobs (
    id bigint generated by default as identity primary key,
    book_id bigint references books(id) on delete set null,
    source_id bigint references library_sources(id) on delete set null,
    file_id bigint references book_files(id) on delete set null,
    status varchar(40) not null,
    message text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists plugin_registry (
    plugin_id varchar(120) primary key,
    display_name varchar(255) not null,
    supported_extensions_json text not null,
    capabilities_json text not null,
    updated_at timestamp with time zone not null
);

create table if not exists plugin_error_logs (
    id bigint generated by default as identity primary key,
    plugin_id varchar(120) not null,
    source_path text,
    error_message text not null,
    created_at timestamp with time zone not null
);
